modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="customrecipe"
version="${version}"
displayName="Custom Recipe"
authors="zazac1"
description='''Create, manage, enable, disable and assign custom crafting recipes globally or per world.'''
logoFile="assets/customrecipe/icon.png"

[[dependencies.customrecipe]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.customrecipe]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.customrecipe]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.136,)"
ordering="NONE"
side="CLIENT"

[[dependencies.customrecipe]]
modId="jei"
mandatory=false
versionRange="[15.20.0,)"
ordering="AFTER"
side="CLIENT"
